Using std::move() for uci parameter.
projectceladon/libvhal-client pull request #12
Opened 2023-06-28 05:57 UTC by bing8deng

uci parameter use std::move().
Reset mFd to -1 in decontractor.

Tracked-On: OAM-110937
Change-Id: I5e10077e1a73d77315115cf65c764158ddb72772

2023-06-28 14:30 UTC, dvrogozh commented on source/virtual_input_receiver.cc
> +        mFd = -1;
this assignment in destructor does not make sense - it's useless.

2023-06-28 20:04 UTC, dvrogozh requested changes
Update commit message and remove "Reset mFd to -1 in decontractor." since you dropped this from the change. Also, there is no such term decontractor, there is term destructor.

2023-07-05 15:44 UTC, dvrogozh approved these changes

2023-07-07 02:00 UTC, JeevakaPrabu approved these changes

2023-07-07 02:00 UTC, merged