aic-emu: Support for Resolution Change
projectceladon/libvhal-client pull request #5
Opened 2023-01-06 10:27 UTC by sandeep-maddipatla

This commit also supports cases where the test content supplied doesn't match the input profile resolution. 
- This is required to support tests where the game resolution changes
- Note that the app still expects the test clip to be larger than or equal to what the profile requires

A minor refactoring is done to support this: Moved surface parameter initialization into the CmdHandler class from the GfxHandler class, due to the former class having better access to the required data (width and stride parameters)

Related Jira: VSMGWL-51998

2023-01-09 22:42 UTC, dvrogozh requested changes
minor changes suggested/requested

2023-01-09 22:42 UTC, dvrogozh commented on aic-emu/CmdHandler.cc
> +	else
remove tab

2023-01-11 22:48 UTC, sandeep-maddipatla commented on aic-emu/CmdHandler.cc
> +	else
done

2023-01-11 22:53 UTC, sandeep-maddipatla commented on aic-emu/CmdHandler.cc
> +    auto src = new uint8_t[srcStride];
I think a memory blob is more suitable here, as we are using this structure for copy ops. We are deallocating it in the same function, so it should be safe.

2023-01-12 01:06 UTC, dvrogozh commented on aic-emu/CmdHandler.cc
> +    auto src = new uint8_t[srcStride];
ok, that's not critical

2023-01-12 01:07 UTC, dvrogozh approved these changes
looks good

2023-01-24 19:49 UTC, merged